package com.hireflow.entity.enums;

public enum NotificationType {
    APPLICATION_SUBMITTED,
    APPLICATION_STATUS_CHANGED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_RESCHEDULED,
    INTERVIEW_CANCELLED,
    INTERVIEW_FEEDBACK_SUBMITTED,
    JOB_POSTED,
    ACCOUNT_STATUS_CHANGED,
    PASSWORD_CHANGED,
    GENERAL
}