server:
  port: 8081

spring:
  application:
    name: hireflow

  datasource:
    url: jdbc:postgresql://localhost:5432/hireflow_db
    username: postgres
    password: Qwerty123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG